// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// //  import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     // if (kIsWeb) {
//     //   throw UnsupportedError(
//     //     'DefaultFirebaseOptions have not been configured for web - '
//     //         'you can reconfigure this by running the FlutterFire CLI again.',
//     //   );
//     // }
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//               'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static FirebaseOptions android = FirebaseOptions(
//     //  apiKey: 'AIzaSyAgZyAGM-rTHpaZEes4h4HLtxKUHq2fW7U',
//     apiKey: 'AIzaSyAn9Ny2uoVOdtZxSHPAxsbCEGrdTa6zlLo',
//     appId: '1:443264678540:android:95dc0fd84038f7adc0d9a9',
//     messagingSenderId: '443264678540',
//     projectId: 'paintlib-3a808',
//     storageBucket: 'paintlib-3a808.firebasestorage.app',
//   );
//
//   static FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA718CxBrM2yPTHFLgrAUfSrnpjeD2enME',
//     appId: '1:850373221209:android:32e5a4e743af889d31ca48',
//     messagingSenderId: '850373221209',
//     projectId: 'paintlib-da981',
//     storageBucket: 'paintlib-da981.firebasestorage.app',
//     // androidClientId:
//     // '823919844465-m6p0v37145lghuj0eamib2c7qtv48lf4.apps.googleusercontent.com',
//     // iosClientId:
//     // '823919844465-8du57g40egqumip40n48a7ndagc4b6el.apps.googleusercontent.com',
//     // iosBundleId: 'sphere-school-app',
//   );
//
//
//   static FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAKyj-HZFuRyYZl09k-05YEY3C3ZOMTL7o',
//     appId: '1:390493233688:web:8a76219740bd9a636fd96d',
//     messagingSenderId: '390493233688',
//     projectId: 'sphere-school-app',
//     storageBucket: 'sphere-school-app.firebasestorage.app',
//
//   );
//
//
// }
